# Generated by Django 5.1.3 on 2024-12-17 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("s3_url", models.URLField()),
                (
                    "upload_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("checksum", models.CharField(blank=True, max_length=255, null=True)),
                ("food_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"ordering": ["-upload_time"],},
        ),
    ]
